<!DOCTYPE html>

<html lang="en">
    <head>
        <link rel="stylesheet" type="text/css" href="../../style/StartLayout.css">
		<link rel="stylesheet" type="text/css" href="../../style/dropdownmenue.css">
        <meta charset="utf-8" />
        <title>YourSpec</title>
    </head>
    <body>
		<?php include('header.php'); ?>
		<div class="menuebox">
			<div class="ganzlinksbox">
				<h2>Datenschutz</h2>
			</div>
			<?php include('top-right-menu.php'); ?>
		</div>
		<br>
		<div class="hauptinfo">
			<p><strong>Verantwortlicher f&uuml;r die Datenverarbeitung ist:</strong><br /> Martin Luddeneit<br /> Kahlaer Straße 14<br /> 07768 Hummelshain<br /> Deutschland<br /> <br /> support@yourspec.de</p>
			<p>Wir freuen uns &uuml;ber Ihr Interesse an unserem Online-Shop. Der Schutz Ihrer Privatsph&auml;re ist f&uuml;r uns sehr wichtig. Nachstehend informieren wir Sie ausf&uuml;hrlich &uuml;ber den Umgang mit Ihren Daten.</p> <p> </p>
			<p><strong>1.&nbsp;Zugriffsdaten und Hosting</strong></p> <p> </p>
			<p>Sie k&ouml;nnen unsere Webseiten besuchen, ohne Angaben zu Ihrer Person zu machen. Bei jedem Aufruf einer Webseite speichert der Webserver lediglich automatisch ein sogenanntes Server-Logfile, das z.B. den Namen der angeforderten Datei, Ihre IP-Adresse, Datum und Uhrzeit des Abrufs, &uuml;bertragene Datenmenge und den anfragenden Provider (Zugriffsdaten) enth&auml;lt und den Abruf dokumentiert.</p> <p>Diese Zugriffsdaten werden ausschlie&szlig;lich zum Zwecke der Sicherstellung eines st&ouml;rungsfreien Betriebs der Seite sowie der Verbesserung unseres Angebots ausgewertet. Dies dient gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f DSGVO der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer korrekten Darstellung unseres Angebots. Alle Zugriffsdaten werden sp&auml;testens sieben Tage nach Ende Ihres Seitenbesuchs gel&ouml;scht.</p> <p> </p>
			<p><strong>Hostingdienstleistungen durch einen Drittanbieter</strong><br /> Im Rahmen einer Verarbeitung in unserem Auftrag erbringt ein Drittanbieter f&uuml;r uns die Dienste zum Hosting und zur Darstellung der Webseite. Alle Daten, die im Rahmen der Nutzung dieser Webseite oder in daf&uuml;r vorgesehenen Formularen im Onlineshop wie folgend beschrieben erhoben werden, werden auf seinen Servern verarbeitet. Eine Verarbeitung auf anderen Servern findet nur in dem hier erl&auml;uterten Rahmen statt.<strong> </strong></p> <p>Dieser Dienstleister sitzt innerhalb eines Landes der Europ&auml;ischen Union oder des Europ&auml;ischen Wirtschaftsraums.</p> <p> </p> <p> </p>
			<p><strong>2.&nbsp;Datenerhebung und -verwendung zur Vertragsabwicklung, Kontaktaufnahme und bei Er&ouml;ffnung eines Kundenkontos</strong></p> <p> </p>
			<p>Wir erheben personenbezogene Daten, wenn Sie uns diese im Rahmen Ihrer Bestellung, bei einer Kontaktaufnahme mit uns (z.B. per Kontaktformular oder E-Mail) oder bei Er&ouml;ffnung eines Kundenkontos freiwillig mitteilen. Pflichtfelder werden als solche gekennzeichnet, da wir in diesen F&auml;llen die Daten zwingend zur Vertragsabwicklung, bzw. zur Bearbeitung Ihrer Kontaktaufnahme oder Er&ouml;ffnung des Kundenkontos ben&ouml;tigen und Sie ohne deren Angabe die Bestellung und/ oder die Kontoer&ouml;ffnung nicht abschlie&szlig;en, bzw. die Kontaktaufnahme nicht versenden k&ouml;nnen. Welche Daten erhoben werden, ist aus den jeweiligen Eingabeformularen ersichtlich.</p> <p>Wir verwenden die von ihnen mitgeteilten Daten gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. b DSGVO zur Vertragsabwicklung und Bearbeitung Ihrer Anfragen. Nach vollst&auml;ndiger Abwicklung des Vertrages oder L&ouml;schung Ihres Kundenkontos werden Ihre Daten f&uuml;r die weitere Verarbeitung eingeschr&auml;nkt und nach Ablauf der steuer- und handelsrechtlichen Aufbewahrungsfristen gel&ouml;scht, sofern Sie nicht ausdr&uuml;cklich in eine weitere Nutzung Ihrer Daten eingewilligt haben oder wir uns eine dar&uuml;ber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und &uuml;ber die wir Sie in dieser Erkl&auml;rung informieren. Die L&ouml;schung Ihres Kundenkontos ist jederzeit m&ouml;glich und kann entweder durch eine Nachricht an die unten beschriebene Kontaktm&ouml;glichkeit oder &uuml;ber eine daf&uuml;r vorgesehene Funktion im Kundenkonto erfolgen.</p>
			<p><strong>3.&nbsp;Datenweitergabe</strong></p> <p> </p>
			<p>Zur Vertragserf&uuml;llung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. b DSGVO geben wir Ihre Daten an das mit der Lieferung beauftragte Versandunternehmen weiter, soweit dies zur Lieferung bestellter Waren erforderlich ist. Je nach dem, welchen Zahlungsdienstleister Sie im Bestellprozess ausw&auml;hlen, geben wir zur Abwicklung von Zahlungen die hierf&uuml;r erhobenen Zahlungsdaten an das mit der Zahlung beauftragte Kreditinstitut und ggf. von uns beauftragte Zahlungsdienstleister weiter bzw. an den ausgew&auml;hlten Zahlungsdienst. Zum Teil erheben die ausgew&auml;hlten Zahlungsdienstleister diese Daten auch selbst, soweit Sie dort ein Konto anlegen. In diesem Fall m&uuml;ssen Sie sich im Bestellprozess mit Ihren Zugangsdaten bei dem Zahlungsdienstleister anmelden. Es gilt insoweit die Datenschutzerkl&auml;rung des jeweiligen Zahlungsdienstleisters.</p> <p> </p> <p> </p>
			<p><strong>Datenweitergabe an Inkassounternehmen</strong><br /> Zur Vertragserf&uuml;llung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. b DSGVO geben wir Ihre Daten an ein beauftragtes Inkassounternehmen weiter, soweit unsere Zahlungsforderung trotz vorausgegangener Mahnung nicht beglichen wurde. In diesem Fall wird die Forderung unmittelbar vom Inkassounternehmen eingetrieben. Dar&uuml;ber hinaus dient die Weitergabe der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer effektiven Geltendmachung bzw. Durchsetzung unserer Zahlungsforderung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f DSGVO.<br /> </p> <p> </p>
			<p><strong>4.&nbsp;E-Mail-Newsletter </strong></p> <p> </p>
			<p><strong>E-Mail-Werbung mit Anmeldung zum Newsletter</strong><br /> Wenn Sie sich zu unserem Newsletter anmelden, verwenden wir die hierf&uuml;r erforderlichen oder gesondert von Ihnen mitgeteilten Daten, um Ihnen regelm&auml;&szlig;ig unseren E-Mail-Newsletter aufgrund Ihrer Einwilligung gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. a DSGVO zuzusenden.</p>
			<p>Die Abmeldung vom Newsletter ist jederzeit m&ouml;glich und kann entweder durch eine Nachricht an die unten beschriebene Kontaktm&ouml;glichkeit oder &uuml;ber einen daf&uuml;r vorgesehenen Link im Newsletter erfolgen.
			Nach Abmeldung l&ouml;schen wir Ihre E-Mail-Adresse aus der Empf&auml;ngerliste, soweit Sie nicht ausdr&uuml;cklich in eine weitere Nutzung Ihrer Daten eingewilligt haben oder wir uns eine dar&uuml;ber hinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und &uuml;ber die wir Sie in dieser Erkl&auml;rung informieren.
			</p><p><strong>5.&nbsp;Cookies</strong></p>
			<p>Um den Besuch unserer Website attraktiv zu gestalten und die Nutzung bestimmter Funktionen zu erm&ouml;glichen, um passende Produkte anzuzeigen oder zur Marktforschung verwenden wir auf verschiedenen Seiten sogenannte Cookies. Dies dient der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer optimierten Darstellung unseres Angebots gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f DSGVO. Cookies sind kleine Textdateien, die automatisch auf Ihrem Endger&auml;t gespeichert werden. Einige der von uns verwendeten Cookies werden nach Ende der Browser-Sitzung, also nach Schlie&szlig;en Ihres Browsers, wieder gel&ouml;scht (sog. Sitzungs-Cookies). Andere Cookies verbleiben auf Ihrem Endger&auml;t und erm&ouml;glichen uns, Ihren Browser beim n&auml;chsten Besuch wiederzuerkennen (persistente Cookies). Die Dauer der Speicherung k&ouml;nnen Sie der &Uuml;bersicht in den Cookie-Einstellungen Ihres Webbrowsers entnehmen. Sie k&ouml;nnen Ihren Browser so einstellen, dass Sie &uuml;ber das Setzen von Cookies informiert werden und einzeln &uuml;ber deren Annahme entscheiden oder die Annahme von Cookies f&uuml;r bestimmte F&auml;lle oder generell ausschlie&szlig;en. Jeder Browser unterscheidet sich in der Art, wie er die Cookie-Einstellungen verwaltet. Diese ist in dem Hilfemen&uuml; jedes Browsers beschrieben, welches Ihnen erl&auml;utert, wie Sie Ihre Cookie-Einstellungen &auml;ndern k&ouml;nnen. Diese finden Sie f&uuml;r die jeweiligen Browser unter den folgenden Links:</p> <p><a href="https://support.microsoft.com/de-de/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank">Internet Explorer&trade;</a><br /> <a href="https://support.apple.com/de-de/guide/safari/sfri11471/12.0/mac/10.14" target="_blank">Safari&trade;</a><br /> <a href="https://support.google.com/chrome/answer/95647?hl=de&amp;hlrm=en" target="_blank">Chrome&trade;</a><br /> <a href="https://support.mozilla.org/de/kb/cookies-erlauben-und-ablehnen" target="_blank">Firefox&trade;</a><br /> <a href="https://help.opera.com/de/latest/web-preferences/#cookies" target="_blank">Opera&trade;</a><br /> Bei der Nichtannahme von Cookies kann die Funktionalit&auml;t unserer Website eingeschr&auml;nkt sein.</p>
			<p><strong>6.&nbsp;Online-Marketing</strong></p>
			<p><strong>Google Maps</strong><br /> Diese Website verwendet Google Maps zur visuellen Darstellung von geographischen Informationen. Google Maps ist ein Angebot der Google Ireland Limited, einer nach irischem Recht eingetragenen und betriebenen Gesellschaft mit Sitz in Gordon House, Barrow Street, Dublin 4, Irland (<a href="http://www.google.de" target="_blank">www.google.de</a>). Dies dient der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer optimierten Darstellung unseres Angebots sowie einer leichten Erreichbarkeit unserer Standorte gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f) DSGVO.<br /> Bei der Verwendung von Google Maps werden von Google Daten &uuml;ber die Nutzung der Maps-Funktionen durch Webseitenbesucher &uuml;bermittelt bzw. verarbeitet, wozu insbesondere die IP-Adresse sowie Standortdaten geh&ouml;ren k&ouml;nnen. Wir haben keinen Einfluss auf diese Datenverarbeitung.<br /> Soweit Informationen auf Server von Google in den USA &uuml;bertragen und dort gespeichert werden, ist die amerikanische Gesellschaft Google LLC unter dem EU-US-Privacy Shield zertifiziert. Ein aktuelles Zertifikat kann <a href="https://www.privacyshield.gov/list" target="_blank">hier</a> eingesehen werden. Aufgrund dieses Abkommens zwischen den USA und der Europ&auml;ischen Kommission hat letztere f&uuml;r unter dem Privacy Shield zertifizierte Unternehmen ein angemessenes Datenschutzniveau festgestellt. <br /> Um den Service von Google Maps zu deaktivieren und damit die Daten&uuml;bermittlung an Google zu verhindern, m&uuml;ssen Sie die Java-Script-Funktion in Ihrem Browser deaktivieren. In diesem Fall kann Google Maps nicht bzw. nur eingeschr&auml;nkt genutzt werden. <br /> Weitergehende Informationen &uuml;ber die Datenverarbeitung durch Google finden Sie in den Datenschutzhinweisen von <a href="https://www.google.com/privacypolicy.html" target="_blank">Google</a>. Die Nutzungsbedingungen f&uuml;r <a href="https://www.google.com/intl/de_de/help/terms_maps.html" target="_blank">Google Maps</a> beinhalten detaillierte Informationen zum Kartendienst. <br /> Die Datenverarbeitung erfolgt auf Grundlage einer Vereinbarung zwischen gemeinsam Verantwortlichen gem&auml;&szlig; Art. 26 DSGVO, die Sie <a href="https://privacy.google.com/intl/de/businesses/mapscontrollerterms/" target="_blank">hier</a> einsehen k&ouml;nnen.</p> <p> </p>
			<p><strong>7.&nbsp;Social Media</strong></p>
			<p><strong>Verwendung von Social Plugins von Instagram, unter Verwendung der Shariff-L&ouml;sung.</strong></p> <p>Auf unserer Website werden Social Buttons von sozialen Netzwerken verwendet.</p> <p>Dies dient der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer optimalen Vermarktung unseres Angebots gem&auml;&szlig; Art. 6 Abs. 1 S. 1 lit. f DSGVO. Um den Schutz Ihrer Daten beim Besuch unserer Website zu erh&ouml;hen, sind diese Buttons nicht uneingeschr&auml;nkt als Plugins, sondern lediglich unter Verwendung eines HTML-Links in die Seite eingebunden. Diese Einbindung gew&auml;hrleistet, dass beim Aufruf einer Seite unseres Webauftritts, die solche Buttons enth&auml;lt, noch keine Verbindung mit den Servern des Anbieters des jeweiligen sozialen Netzwerks hergestellt wird.</p> <p>Klicken Sie auf einen der Buttons, &ouml;ffnet sich ein neues Fenster Ihres Browsers und ruft die Seite des jeweiligen Diensteanbieters auf, auf der Sie (ggf. nach Eingabe Ihrer Login-Daten) z.B. den Like- oder Share-Button bet&auml;tigen k&ouml;nnen.</p>
			<p>Zweck und Umfang der Datenerhebung und die weitere Verarbeitung und Nutzung der Daten durch die Anbieter auf deren Seiten sowie eine Kontaktm&ouml;glichkeit und Ihre diesbez&uuml;glichen Rechte und Einstellungsm&ouml;glichkeiten zum Schutz Ihrer Privatsph&auml;re entnehmen Sie bitte den Datenschutzhinweisen der Anbieter:</p>
			<p><a href="https://help.instagram.com/155833707900388" target="_blank">https://help.instagram.com/155833707900388</a></p>
			<p><strong>Unsere Onlinepr&auml;senz auf Instagram</strong></p> <p>Unsere Pr&auml;senz auf sozialen Netzwerken und Plattformen dient einer besseren, aktiven Kommunikation mit unseren Kunden und Interessenten. Wir informieren dort &uuml;ber unsere Produkte und laufende Sonderaktionen.<br /> Bei dem Besuch unserer Onlinepr&auml;senzen in sozialen Medien k&ouml;nnen Ihre Daten f&uuml;r Marktforschungs- und Werbezwecke automatisch erhoben und gespeichert werden. Aus diesen Daten werden unter Verwendung von Pseudonymen sog. Nutzungsprofile erstellt. Diese k&ouml;nnen verwendet werden, um z.B. Werbeanzeigen innerhalb und au&szlig;erhalb der Plattformen zu schalten, die mutma&szlig;lich Ihren Interessen entsprechen. Zu diesem Zweck werden im Regelfall Cookies auf Ihrem Endger&auml;t eingesetzt. In diesen Cookies werden das Besucherverhalten und die Interessen der Nutzer gespeichert. Dies dient gem. Art. 6 Abs. 1 lit. f. DSGVO der Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen an einer optimierten Darstellung unseres Angebots und effektiver Kommunikation mit den Kunden und Interessenten. Falls Sie von den jeweiligen Social-Media Plattformbetreibern um eine Einwilligung (Einverst&auml;ndnis) in die Datenverarbeitung gebeten werden, z.B. mit Hilfe einer Checkbox, ist die Rechtsgrundlage der Datenverarbeitung Art. 6 Abs. 1 lit. a DSGVO.<br /> Soweit die vorgenannten Social-Media Plattformen ihren Hauptsitz in den USA haben, gilt Folgendes: F&uuml;r die USA liegt ein Angemessenheitsbeschluss der Europ&auml;ischen Kommission vor. Dieser geht zur&uuml;ck auf den EU-US Privacy Shield. Ein aktuelles Zertifikat f&uuml;r das jeweilige Unternehmen kann <a href="https://www.privacyshield.gov/list" target="_blank">hier</a> eingesehen werden.<br /> Die detaillierten Informationen zur Verarbeitung und Nutzung der Daten durch die Anbieter auf deren Seiten sowie eine Kontaktm&ouml;glichkeit und Ihre diesbez&uuml;glichen Rechte und Einstellungsm&ouml;glichkeiten zum Schutz Ihrer Privatsph&auml;re, insbesondere Widerspruchsm&ouml;glichkeiten (Opt-Out), entnehmen Sie bitte den unten verlinkten Datenschutzhinweisen der Anbieter. Sollten Sie diesbez&uuml;glich dennoch Hilfe ben&ouml;tigen, k&ouml;nnen Sie sich an uns wenden.</p>
			<p>Instagram: <a href="https://help.instagram.com/519522125107875" target="_blank">https://help.instagram.com/519522125107875</a></p>
			<p>Widerspruchsm&ouml;glichkeit (Opt-Out):</p>
			<p>Instagram: <a href="https://help.instagram.com/519522125107875" target="_blank">https://help.instagram.com/519522125107875</a></p>
			<p><strong>8.&nbsp;Kontaktm&ouml;glichkeiten und Ihre Rechte</strong></p> <p> <p> </p> </p>
			<p>Als Betroffener haben Sie folgende Rechte:</p> <ul> <li>gem&auml;&szlig; Art. 15 DSGVO das Recht, in dem dort bezeichneten Umfang Auskunft &uuml;ber Ihre von uns verarbeiteten personenbezogenen Daten zu verlangen;</li> <li>gem&auml;&szlig; Art. 16 DSGVO das Recht, unverz&uuml;glich die Berichtigung unrichtiger oder Vervollst&auml;ndigung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen;</li> <li>gem&auml;&szlig; Art. 17 DSGVO das Recht, die L&ouml;schung Ihrer bei uns gespeicherten personenbezogenen Daten zu verlangen, soweit nicht die weitere Verarbeitung <ul> <li>zur Aus&uuml;bung des Rechts auf freie Meinungs&auml;u&szlig;erung und Information;</li> <li>zur Erf&uuml;llung einer rechtlichen Verpflichtung;</li> <li>aus Gr&uuml;nden des &ouml;ffentlichen Interesses oder</li> <li>zur Geltendmachung, Aus&uuml;bung oder Verteidigung von Rechtsanspr&uuml;chen erforderlich ist;</li> </ul> </li> <li>gem&auml;&szlig; Art. 18 DSGVO das Recht, die Einschr&auml;nkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, soweit <ul> <li>die Richtigkeit der Daten von Ihnen bestritten wird;</li> <li>die Verarbeitung unrechtm&auml;&szlig;ig ist, Sie aber deren L&ouml;schung ablehnen;</li> <li>wir die Daten nicht mehr ben&ouml;tigen, Sie diese jedoch zur Geltendmachung, Aus&uuml;bung oder Verteidigung von Rechtsanspr&uuml;chen ben&ouml;tigen oder</li> <li>Sie gem&auml;&szlig; Art. 21 DSGVO Widerspruch gegen die Verarbeitung eingelegt haben;</li> </ul> </li> <li>gem&auml;&szlig; Art. 20 DSGVO das Recht, Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, g&auml;ngigen und maschinenlesebaren Format zu erhalten oder die &Uuml;bermittlung an einen anderen Verantwortlichen zu verlangen;</li> <li>gem&auml;&szlig; Art. 77 DSGVO das Recht, sich bei einer Aufsichtsbeh&ouml;rde zu beschweren. In der Regel k&ouml;nnen Sie sich hierf&uuml;r an die Aufsichtsbeh&ouml;rde Ihres &uuml;blichen Aufenthaltsortes oder Arbeitsplatzes oder unseres Unternehmenssitzes wenden.</li> </ul> <p>Bei Fragen zur Erhebung, Verarbeitung oder Nutzung Ihrer personenbezogenen Daten, bei Ausk&uuml;nften, Berichtigung, Einschr&auml;nkung oder L&ouml;schung von Daten sowie Widerruf erteilter Einwilligungen oder Widerspruch gegen eine bestimmte Datenverwendung wenden Sie sich bitte direkt an uns &uuml;ber die Kontaktdaten in unserem Impressum.</p>
			<table border="1" cellpadding="1" cellspacing="1" style="width:100%"> <tbody> <tr> <td> <p><strong>Widerspruchsrecht</strong><br /> Soweit wir zur Wahrung unserer im Rahmen einer Interessensabw&auml;gung &uuml;berwiegenden berechtigten Interessen personenbezogene Daten wie oben erl&auml;utert verarbeiten, k&ouml;nnen Sie dieser Verarbeitung mit Wirkung f&uuml;r die Zukunft widersprechen. Erfolgt die Verarbeitung zu Zwecken des Direktmarketings, k&ouml;nnen Sie dieses Recht jederzeit wie oben beschrieben aus&uuml;ben. Soweit die Verarbeitung zu anderen Zwecken erfolgt, steht Ihnen ein Widerspruchsrecht nur bei Vorliegen von Gr&uuml;nden, die sich aus Ihrer besonderen Situation ergeben, zu.</p> <p>Nach Aus&uuml;bung Ihres Widerspruchsrechts werden wir Ihre personenbezogenen Daten nicht weiter zu diesen Zwecken verarbeiten, es sei denn, wir k&ouml;nnen zwingende schutzw&uuml;rdige Gr&uuml;nde f&uuml;r die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten &uuml;berwiegen, oder wenn die Verarbeitung der Geltendmachung, Aus&uuml;bung oder Verteidigung von Rechtsanspr&uuml;chen dient</p> <p>Dies gilt nicht, wenn die Verarbeitung zu Zwecken des Direktmarketings erfolgt. Dann werden wir Ihre personenbezogenen Daten nicht weiter zu diesem Zweck verarbeiten.</p> <p> </p> </td> </tr> </tbody> </table>
			<br><p><i><a target="_blank" title="Datenschutzerklärung" href="https://shop.trustedshops.com/de/rechtstexte/">Datenschutzerklärung</a> erstellt mit dem <a target="_blank" title="Trusted Shops" href="https://shop.trustedshops.com/de/">Trusted Shops</a> Rechtstexter in Kooperation mit <a target="_blank" title="Wilde Beuger Solmecke Rechtsanwälte" href="https://www.wbs-law.de/" rel="nofollow">Wilde Beuger Solmecke Rechtsanwälte</a>.</i></p>
		</div>
	
		<br>
	
		<?php include('footer.php'); ?>
    </body>
</html>